steps:
  # Step 1: Initialize Terraform
  - name: 'hashicorp/terraform:1.5.7'
    id: 'terraform-init'
    entrypoint: 'terraform'
    args:
      - 'init'
      - '-backend-config=bucket=gcs-bigquery-batch-data-bucket'
      - '-backend-config=prefix=terraform/state'

  # Step 2: Terraform Plan
  - name: 'hashicorp/terraform:1.5.7'
    id: 'terraform-plan'
    entrypoint: 'terraform'
    args:
      - 'plan'
      - '-out=tfplan'

  # Step 3: Terraform Apply (this step will apply the plan created in Step 2)
  - name: 'hashicorp/terraform:1.5.7'
    id: 'terraform-apply'
    entrypoint: 'terraform'
    args:
      - 'apply'
      - '-auto-approve'
      - 'tfplan'

# Timeout for the build process
timeout: '1200s'  # 20 minutes

# Logging options
options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging for build logs

