steps:
  # Step 1: Set up Terraform backend (GCS) and initialize
  - name: 'hashicorp/terraform:1.5.7'  # ✅ Official HashiCorp image
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init \
          -backend-config="bucket=migrationproject62718-terraform-state" \
          -backend-config="prefix=terraform/state"

  # Step 2: Apply Terraform configuration with auto-approve
  - name: 'hashicorp/terraform:1.5.7'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform apply -auto-approve

options:
  logging: CLOUD_LOGGING_ONLY   # ✅ Push logs to Cloud Logging (for observability)
timeout: 9200s
